# Generated by Django 5.2.4 on 2025-10-21 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_details', models.TextField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('patient_type', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('isn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_web.healthrecord')),
            ],
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='usn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_web.student'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='isn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_web.teacher'),
        ),
    ]
